Repository intellistream/SAGE, pull requests merged in 2025-09, with the labels that each got.

#555 🔧 fix: 完善C扩展自动编译和CI/CD流程
  .github/workflows/build-release.yml
  packages/sage-kernel/setup.py
  packages/sage-kernel/src/sage/kernel/enterprise/sage_queue/build.sh
  packages/sage-middleware/setup.py
  tools/ci-cd/test_ci_build.sh
Labels: bug

#715 refactor(script): move to tools
  packages/sage-tools/src/sage/tools/studio/scripts/setup_frontend.sh
  packages/sage-tools/src/sage/tools/studio/scripts/studio_demo.sh
  packages/sage-tools/src/sage/tools/studio/scripts/studio_manager.sh
  scripts/README.md
  scripts/TEST_SCRIPTS_EXAMPLES.md
  scripts/fix_conda_tos.sh
  scripts/quick_publish_all.sh
  tools/conda/conda_utils.sh
  tools/conda/fix_conda_tos.sh
  tools/conda/install-sage-conda.sh
  tools/conda/sage-conda.sh
  tools/diagnostics/check_compatibility.py
  tools/diagnostics/check_packages_status.sh
  tools/diagnostics/diagnose_sage.py
  tools/maintenance/quick_cleanup.sh
  tools/maintenance/sage-jobmanager.sh
  tools/maintenance/submodule_manager.sh
  tools/publishing/PUBLISH_SCRIPTS_README.md
  tools/publishing/quick_publish_all.sh
  tools/publishing/update_sage_packages.sh
  tools/tests/test_ray_quick.sh
  tools/utils/common_utils.sh
  tools/utils/config.sh
  tools/utils/logging.sh
  tools/utils/python_bridge.sh
  tools/version-management/version_manager.sh
Labels: enhancement

#732 增加了mcp测试
  packages/sage-libs/tests/lib/agents/test_mcp_registry.py
  packages/sage-libs/tests/lib/agents/test_mcp_server.py
Labels: enhancement

#724 Feature/增加多种格式文档的loader #508
  examples/config/config_dense_milvus.yaml
  examples/data/qa_knowledge_base.docx
  examples/data/qa_knowledge_base.md
  examples/data/qa_knowledge_base.pdf
  examples/data/qa_knowledge_chromaDB.txt
  examples/data/qa_knowledge_rag.md
  examples/rag/build_chroma_index.py
  examples/rag/build_milvus_dense_index.py
  examples/rag/build_milvus_sparse_index.py
  packages/sage-libs/pyproject.toml
  packages/sage-libs/src/sage/libs/rag/document_loaders.py
Labels: enhancement

#749 fix(install): redesign installation modes to ensure sage CLI availability
  .github/WORKFLOW_OPTIMIZATION.md
  .github/workflows/ci.yml
  .github/workflows/dev-ci.yml
  .github/workflows/dev-ci.yml.backup
  .github/workflows/only-main-dev.yml
  .github/workflows/todo-to-issue-pr.yml
  .gitignore
  README.md
  ci-local-validation-report.md
  ci-workflow-analysis.md
  examples/agents/agent.py
  examples/agents/tools/__init__.py
  examples/agents/tools/arxiv_search_tool.py
  examples/agents/tools/demo_arxiv_search.py
  examples/config/config_source_local.yaml
  examples/rag/build_chroma_index.py
  examples/rag/build_milvus_dense_index.py
  examples/rag/build_milvus_sparse_index.py
  examples/rag/qa_without_retrieval_local.py
  packages/sage-kernel/pyproject.toml
  packages/sage-kernel/tests/unit/kernel/runtime/communication/queue/test_queue_descriptor.py
  packages/sage-libs/pyproject.toml
  packages/sage-libs/src/sage/libs/agents/planning/llm_planner.py
  packages/sage-libs/src/sage/libs/rag/document_loaders.py
  packages/sage-libs/src/sage/libs/rag/generator.py
  packages/sage-libs/tests/lib/agents/test_mcp_registry.py
  packages/sage-libs/tests/lib/agents/test_mcp_server.py
  packages/sage-middleware/pyproject.toml
  packages/sage-middleware/setup.py
  packages/sage-middleware/src/sage/__init__.py
  packages/sage-middleware/src/sage/middleware/components/sage_db/sage_db.py
  packages/sage-tools/README.md
  packages/sage-tools/pyproject.toml
  packages/sage-tools/src/sage/tools/_version.py
  packages/sage-tools/src/sage/tools/cli/README.md
  packages/sage-tools/src/sage/tools/cli/commands/dev/simple_main.py
  packages/sage-tools/src/sage/tools/cli/commands/pypi.py
  packages/sage-tools/src/sage/tools/cli/commands/studio.py
  packages/sage-tools/src/sage/tools/cli/commands/version.py
  packages/sage-tools/src/sage/tools/cli/main.py
  packages/sage-tools/src/sage/tools/cli/managers/studio_manager.py
  packages/sage-tools/src/sage/tools/dev/core/bytecode_compiler.py
  packages/sage-tools/src/sage/tools/studio/config/backend/api.py
  packages/sage-tools/src/sage/tools/web_ui/app.py
  packages/sage-tools/tests/pypi/test_install_modes.py
  packages/sage-tools/tests/pypi/test_install_modes.sh
  packages/sage-tools/tests/pypi/validate_pip_install_complete.py
  packages/sage/pyproject.toml
  quickstart.sh
  tools/__init__.py
  tools/env_config.py
  tools/install/download_tools/argument_parser.sh
  tools/install/fixes/README.md
  tools/install/fixes/environment_doctor.sh
  tools/install/fixes/friendly_error_handler.sh
  tools/install/fixes/numpy_fix.sh
  tools/install/installation_table/core_installer.sh
  tools/install/installation_table/main_installer.sh
  tools/tests/conftest.py
  tools/tests/test_examples.py
Labels: enhancement

#770 modify pyproject
  examples/config/config_refiner.yaml
  examples/config/config_source.yaml
  examples/rag/qa_refiner.py
  packages/sage-libs/pyproject.toml
Labels: bug

#817 cleanup
  examples/README.md
  examples/agents/agent_workflow_demo.py
  examples/memory/memory_service_demo.py
  examples/memory/run_memory_service_demo.sh
  examples/memory/test_real_memory_service.py
Labels: enhancement

#813 fix agent tests
  packages/sage-libs/tests/lib/agents/test_agent_examples.py
  packages/sage-libs/tests/lib/agents/test_arxiv_tool.py
Labels: bug

#796 socket source done
  packages/sage-libs/src/sage/libs/io_utils/source.py
Labels: algorithm

#840 socket source test done
  examples/tutorials/io_utils/Socketsouce.py
  packages/sage-libs/src/sage/libs/io_utils/source.py
Labels: enhancement

#846 Refinerfix
  packages/sage-libs/src/sage/libs/rag/longrefiner/longrefiner/refiner.py
Labels: bug

#859 Middleware/dependency refactor (#858)
  .gitignore
  packages/sage-middleware/CMakeLists.txt
  packages/sage-middleware/README.md
  packages/sage-middleware/pyproject.toml
  packages/sage-middleware/setup.py
  packages/sage-middleware/src/sage/middleware/components/cmake/pybind11_dependency.cmake
  packages/sage-middleware/src/sage/middleware/components/cmake/sage_shared_dependencies.cmake
  pytest.ini
  tools/install/download_tools/conda_manager.sh
  tools/install/fixes/libstdcxx_fix.sh
  tools/install/installation_table/main_installer.sh
Labels: enhancement
